name: Publish Recipe

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  publish-recipe:
    runs-on: windows-latest

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: 🛠️ Install dotnet tools
      run: dotnet tool restore

    - name: 🔨 Publish Recipe
      env:
        MYGET_API_KEY: ${{ secrets.PUBLISH_MYGET_ORG }}
        NUGET_API_KEY: ${{ secrets.PUBLISH_NUGET_ORG }}
        CHOCO_API_KEY: ${{ secrets.PUBLISH_CHOCOLATEY_ORG }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_CP }}

      run: dotnet cake --target=ContinuousIntegration
