name: Publish Recipe

on: [workflow_dispatch, push, pull_request]

jobs:
  publish-recipe:
    runs-on: ubuntu-latest

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: 🛠️ Install dotnet tools
      run: dotnet tool restore

    - name: 🔨 Publish Recipe
      env:
        MYGET_API_KEY: ${{ secrets.PUBLISH_MYGET_ORG }}
        NUGET_API_KEY: ${{ secrets.PUBLISH_NUGET_ORG }}
        CHOCO_API_KEY: ${{ secrets.PUBLISH_CHOCOLATEY_ORG }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_CP }}

      # TODO: 
      # 1. Change target to Publish for publishing dev builds on MyGet. DONE
      # 2. Figure out process for creating the draft release.
      # 3. Change Target to ContinuousIntegration for full release.
      run: dotnet cake --target=Publish
